# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22-slim AS build

# Install system dependencies required by keytar/smithery
RUN apt-get update && apt-get install -y \
    libsecret-1-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the code and build
COPY . .
RUN npm run build

# Run the smithery build command
RUN npx -y @smithery/cli build -o .smithery/index.cjs

# Production stage
FROM node:22-slim

# Install runtime dependency for libsecret
RUN apt-get update && apt-get install -y \
    libsecret-1-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy built files from the build stage
COPY --from=build /app/.smithery/index.cjs .

# Set the command to run your MCP server
ENTRYPOINT ["node", "index.cjs"]
