[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "doi-mcp"
version = "1.0.0"
description = "DOI resolver MCP server for verifying and citing articles"
requires-python = ">=3.10"
dependencies = ["mcp>=0.1.0", "httpx>=0.24.0"]